# Generated by Django 6.0.3 on 2026-04-15 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0020_delete_descansousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioOndoku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ondoku_atual', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.usuario')),
            ],
        ),
    ]
