# Generated by Django 6.0.3 on 2026-04-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0022_alter_fraseusuario_palavra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telegram_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
