# Generated by Django 6.0.3 on 2026-04-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_word_anki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Id',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
