# Generated by Django 6.0.3 on 2026-04-13 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0017_remove_usuario_lista_user_fraseusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescansoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_descanso', models.TimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.usuario')),
            ],
        ),
    ]
