# Generated by Django 6.0.3 on 2026-04-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_rename_palavras_usuario_palavra_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tela_atual',
            field=models.TextField(default='deslogado'),
        ),
    ]
