# Generated by Django 6.0.3 on 2026-04-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_usuario_tela_atual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='palavras_incial',
            new_name='palavra_incial',
        ),
    ]
