# Generated by Django 6.0.3 on 2026-04-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_delete_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='lista_user',
            field=models.JSONField(default=['OI']),
        ),
    ]
