# Generated by Django 6.0.3 on 2026-03-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_remove_word_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='anki',
            field=models.BooleanField(default=False),
        ),
    ]
