# Generated by Django 6.0.3 on 2026-04-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_rename_palavras_incial_usuario_palavra_incial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='palavra_incial',
            new_name='palavra_inicial',
        ),
    ]
