# Generated by Django 6.0.3 on 2026-04-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0013_usuario_lista_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='lista_user',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='palavra_atual',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='palavra_inicial',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='streak',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tela_atual',
            field=models.TextField(),
        ),
    ]
