# Generated by Django 6.0.3 on 2026-04-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0019_usuario_proximo_estudo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DescansoUsuario',
        ),
    ]
