# Generated by Django 6.0.3 on 2026-04-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_rename_id_usuario_telegram_id_usuario_streak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='palavras',
            new_name='palavra_atual',
        ),
        migrations.AddField(
            model_name='usuario',
            name='palavras_incial',
            field=models.IntegerField(default=0),
        ),
    ]
