# Generated by Django 6.0.3 on 2026-04-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_rename_palavra_incial_usuario_palavra_inicial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
    ]
