# Generated by Django 6.0.3 on 2026-04-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0015_alter_usuario_palavra_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='lista_user',
            field=models.JSONField(verbose_name=['']),
        ),
    ]
