# Generated by Django 6.0.3 on 2026-04-13 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0016_alter_usuario_lista_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='lista_user',
        ),
        migrations.CreateModel(
            name='FraseUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField()),
                ('frase', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.usuario')),
            ],
        ),
    ]
