# Generated by Django 6.0.3 on 2026-04-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0021_usuarioondoku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraseusuario',
            name='palavra',
            field=models.CharField(max_length=100),
        ),
    ]
