# Generated by Django 6.0.3 on 2026-05-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0023_alter_usuario_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reminder_user',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
