# Generated by Django 6.0.3 on 2026-05-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0024_usuario_reminder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='reminder_user',
        ),
        migrations.AddField(
            model_name='usuario',
            name='reminder_minutes',
            field=models.IntegerField(default=1440),
        ),
    ]
