# Generated by Django 6.0.3 on 2026-05-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0025_remove_usuario_reminder_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome_usuario',
            field=models.CharField(default='Cleyton'),
        ),
    ]
