# Generated by Django 6.0.3 on 2026-05-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0025_alter_usuario_reminder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='reminder_user',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
