# Generated by Django 6.0.3 on 2026-05-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0026_alter_usuario_reminder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='reminder_user',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
