# Generated by Django 6.0.3 on 2026-05-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0026_usuario_nome_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reminder_jornada',
            field=models.IntegerField(default=0),
        ),
    ]
