# Generated by Django 6.0.3 on 2026-05-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0027_usuario_reminder_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='reminder_jornada',
            field=models.IntegerField(default=-1),
        ),
    ]
