# Generated by Django 6.0.3 on 2026-05-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0028_alter_usuario_reminder_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='level_ondoku',
            field=models.IntegerField(default=0),
        ),
    ]
