# Generated by Django 6.0.3 on 2026-05-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0028_alter_usuario_reminder_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome_usuario',
            field=models.CharField(default='Cleyton', max_length=60),
        ),
    ]
