# Generated by Django 6.0.3 on 2026-05-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0029_usuario_level_ondoku'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioondoku',
            name='op_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usuarioondoku',
            name='ondoku_atual',
            field=models.IntegerField(default=1),
        ),
    ]
