# Generated by Django 6.0.3 on 2026-05-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0029_alter_usuario_reminder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='reminder_user',
            new_name='reminder_minutes',
        ),
    ]
