# Generated by Django 6.0.3 on 2026-05-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0030_usuarioondoku_op_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='level_ondoku',
            field=models.IntegerField(default=1),
        ),
    ]
