# Generated by Django 6.0.3 on 2026-05-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0031_alter_usuario_level_ondoku'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user_cowndown',
            field=models.IntegerField(default=0),
        ),
    ]
