# Generated by Django 6.0.3 on 2026-05-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0032_usuario_user_cowndown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_cowndown',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
