# Generated by Django 6.0.3 on 2026-05-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0029_alter_usuario_nome_usuario'),
        ('rest_api', '0033_alter_usuario_user_cowndown'),
    ]

    operations = [
    ]
