# Generated by Django 6.0.3 on 2026-04-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_alter_id_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('palavras', models.IntegerField(default=0)),
            ],
        ),
    ]
