# Generated by Django 6.0.3 on 2026-03-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word', models.CharField(primary_key=True, serialize=False)),
                ('setences', models.TextField()),
                ('definition', models.TextField()),
            ],
        ),
    ]
