# Generated by Django 6.0.3 on 2026-04-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0014_alter_usuario_lista_user_alter_usuario_palavra_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='palavra_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='palavra_inicial',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tela_atual',
            field=models.TextField(default='deslogado'),
        ),
    ]
