# Generated by Django 6.0.3 on 2026-04-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0018_descansousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='proximo_estudo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
