# Generated by Django 6.0.3 on 2026-04-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='id',
            field=models.TextField(default=0, primary_key=True, serialize=False),
        ),
    ]
