# Generated by Django 6.0.3 on 2026-04-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id',
            new_name='telegram_id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
